### ISSUE TITLE
几个可以参考的建议

### ISSUE THREAD

**Issue by ghost** [Jarvis-Tang/JieStyle-Two#3]
谢谢Tang 提供这么清爽漂亮的主体, 使用中遇到的部分问题供参考:

-  js外链优化问题
将如下两个 js 从 header.php 移动到 footer.php,以加速页面加载:

jquery.min.js:1.11.3
bootstrap.min.js:3.3.7

这样调整会导致移动端下页面菜单不会加载等问题.

-  移动端显示建议
目前的移动端显示, 需要点击右上角的菜单图标, 然后菜单栏左移, 这是个比较酷炫的设计, 但给人页面显示出问题的感觉, 和主题清爽的调子不太搭啊. 

可以参考其他主题的如下设计: 菜单栏不变, 通过点击右上的图标切换菜单栏下面的内容.

-  表格不显示边框
这个可以通过增加类似如下 CSS定义解决:

``` CSS
table {
    font-family: verdana,arial,sans-serif;
    font-size:11px;
    color:#333333;
    border-width: 1px;
    border-color: #999999;
    border-collapse: collapse;
}
table th {
    background-color:#c3dde0;
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #a9c6c9;
}
table tr {
    background-color:#d4e3e5;
}
table td {
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #a9c6c9;
}

```

其他问题, 建议安装插件  Theme Check 查看.
